import { redirect } from "next/navigation";
import { requireOrganizer } from "@/lib/auth/require-organizer";
import { getPrimaryOrganizationForUser } from "@/lib/data/organization-membership";
import { getOrganizationReport } from "@/lib/data/analytics/organization";
import { coerceDateRange, DATE_RANGES } from "@/lib/data/analytics/date-range";
import {
  ImpactStatGrid,
  MonthlyHoursChart,
  CategoryBreakdown,
  EngagementCard,
  MissionPerformanceTable,
} from "@/components/reports/analytics-cards";
import PrintButton from "@/components/reports/print-button";
import Logo from "@/components/logo";

export const dynamic = "force-dynamic";

const MONTH = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

export default async function PrintReport({ searchParams }: { searchParams: { range?: string } }) {
  const guard = await requireOrganizer();
  if (!guard.ok) {
    if (guard.code === "no_org") redirect("/manage/onboarding");
    redirect(guard.code === "auth" ? "/auth?next=/reports/print" : "/dashboard");
  }

  const range = coerceDateRange(searchParams.range);
  const [org, report] = await Promise.all([
    getPrimaryOrganizationForUser(guard.userId),
    getOrganizationReport(guard.orgId, range),
  ]);
  const rangeLabel = DATE_RANGES.find((r) => r.value === range)?.label ?? "All time";
  const generated = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric", timeZone: "UTC" });

  const byMonth = new Map<string, number>();
  for (const p of report.performance) {
    const key = p.startsAt?.slice(0, 7);
    if (!key) continue;
    byMonth.set(key, (byMonth.get(key) ?? 0) + p.hours);
  }
  const monthly = Array.from(byMonth.entries())
    .sort((a, b) => (a[0] < b[0] ? -1 : 1))
    .slice(-12)
    .map(([k, h]) => ({ label: `${MONTH[Number(k.split("-")[1]) - 1]} ${k.slice(0, 4)}`, hours: Math.round(h * 100) / 100 }));

  return (
    <div style={{ background: "var(--bg-app)", minHeight: "100vh" }} className="print-page">
      <div style={{ maxWidth: 920, margin: "0 auto", padding: "28px 24px 60px" }}>
        {/* top bar (hidden on print) */}
        <div className="print-hide" style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 22 }}>
          <a href="/manage/reports" style={{ fontSize: 13.5, fontWeight: 600, color: "var(--muted-1)" }}>← Back to reports</a>
          <PrintButton />
        </div>

        {/* report header */}
        <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 6 }}>
          <Logo size={30} />
          <span style={{ fontWeight: 800, fontSize: 17 }}>NeighborLoop</span>
        </div>
        <h1 style={{ fontSize: 28, fontWeight: 800, margin: "10px 0 4px", letterSpacing: "-.02em" }}>
          Impact report{org?.name ? ` · ${org.name}` : ""}
        </h1>
        <p style={{ fontSize: 14, color: "var(--muted-2)", margin: "0 0 22px" }}>
          {rangeLabel} · generated {generated}
        </p>

        <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          <ImpactStatGrid summary={report.summary} />
          <MonthlyHoursChart data={monthly} />
          <CategoryBreakdown rows={report.categories} />
          <MissionPerformanceTable rows={report.performance} />
          <EngagementCard engagement={report.engagement} />
        </div>

        <p style={{ fontSize: 12, color: "var(--muted-3)", textAlign: "center", marginTop: 28 }}>
          Generated by NeighborLoop · figures reflect confirmed attendance and issued certificates.
        </p>
      </div>
    </div>
  );
}
